apiVersion: v1
kind: Pod
metadata:
  name: single-pod
  labels:
    version: v1
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports: 
      - containerPort: 80
        protocol: TCP
