apiVersion: v1
kind: Pod
metadata:
  name: vol-pod
  labels:
    version: v1
spec:
  containers:
    - name: nginx
      image: nginx:stable
      ports:
        - containerPort: 80
      volumeMounts:
        - name: local-vol
          mountPath: /usr/share/nginx/html
  volumes:
    - name: local-vol
      hostPath:
        path: /home/vagrant/html
        type: Directory 
  
    
